suite_name: microbench
shared_config: configs/base_llama130_pretrain.yaml

experiments:
  - name: adamw_bench
    overrides:
      run_kind: benchmark
      analysis:
        enable_memory_profile: true
      benchmark:
        enabled: true
        measure_steps: 250
      optimizer:
        name: adamw

  - name: apollo_rank_1_4_bench
    overrides:
      run_kind: benchmark
      analysis:
        enable_memory_profile: true
      benchmark:
        enabled: true
        measure_steps: 250
      optimizer:
        name: apollo
        rank_ratio: 0.25
        granularity: channel
        projection: random
        scale: 1.0

  - name: apollo_rank_1_8_bench
    overrides:
      run_kind: benchmark
      analysis:
        enable_memory_profile: true
      benchmark:
        enabled: true
        measure_steps: 250
      optimizer:
        name: apollo
        rank_ratio: 0.125
        granularity: channel
        projection: random
        scale: 1.0

  - name: apollo_mini_bench
    overrides:
      run_kind: benchmark
      analysis:
        enable_memory_profile: true
      benchmark:
        enabled: true
        measure_steps: 250
      optimizer:
        name: apollo_mini
        rank: 1
        granularity: tensor
        projection: random
        scale: 128.0
